# Generated by Django 2.2 on 2020-08-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200811_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
